---
# Installs and configures the FileStore

- name: Install acl related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - acl

- name: Ensure FileStore directory exists
  file: path=/var/lib/ckan/default owner=www-data state=directory

- name: Ensure Apache can write to FileStore directory
  acl: name=/var/lib/ckan/default entity=www-data etype=user permissions=u+rwx
