---
# This playbook deploys/installs a complete CKAN isolated instance for
# NHSEngland. Assumes a 64bit Ubuntu LTS as the target OS.

- name: install CKAN
  sudo: yes
  user: ubuntu
  hosts: webservers
  roles:
    - ckan

- name: install and configure SOLR
  sudo: yes
  user: ubuntu
  hosts: solr
  roles:
    - solr

- name: install and configure Postgres
  sudo: yes
  user: ubuntu
  hosts: dbservers
  roles:
    - db

- name: install and configure DataStore
  sudo: yes
  user: ubuntu
  hosts: dbservers
  roles:
    - datastore

- name: install and configure FileStore
  sudo: yes
  user: ubuntu
  hosts: webservers
  roles:
    - filestore

- name: install plugins
  sudo: yes
  user: ubuntu
  hosts: webservers
  roles:
    - plugins

- name: configure ckan
  sudo: yes
  user: ubuntu
  hosts: webservers
  tasks:
      - name: configure our CKAN instance
        template: src=config/production.ini dest=/etc/ckan/default/production.ini

      - name: initialise the database
        command: ckan db init


      - name: Set DataStore database permissions
        command: ckan datastore set-permissions postgres


      - name: restart Apache
        service: name=apache2 state=restarted

      - name: restart Nginx
        service: name=nginx state=restarted
